"""
extract.py — pipeline_demo stage 1 of 4 (extract -> transform -> load -> validate).

Mirrors the production extract pattern (src/extract/awards.py + src/api_clients/
usaspending_bulk.py): pull DoD prime-award records from USAspending for ONE agency
and ONE fiscal year at a small page size, then hand the raw slice downstream.

Two paths:
  * --offline (DEFAULT for the demo and CI): read a COMMITTED, deterministic,
    100%%-synthetic raw-JSON fixture. The live USAspending search API is known to
    throw intermittent HTTP 503s under load (documented in
    src/api_clients/usaspending_bulk.py), so the demo never depends on the network.
  * online (opt-in, --online): a real best-effort POST to the USAspending
    spending_by_award endpoint. Provided to show the real shape; NOT used by CI.

The fixture is generated ONCE by `python pipeline_demo/extract.py --generate-fixture`
and committed. It is ~300 rows of clearly-labeled SYNTHETIC data — every value is
deterministically fabricated and represents no real federal award, vendor, or agency.

Run:
  python pipeline_demo/extract.py --offline            # read committed fixture, report count
  python pipeline_demo/extract.py --generate-fixture   # (re)generate the committed fixture
  python pipeline_demo/extract.py --online             # best-effort live pull (not for CI)
"""

import argparse
import json
import random
import sys
from datetime import date, timedelta
from pathlib import Path

DEMO_DIR = Path(__file__).resolve().parent
FIXTURE_PATH = DEMO_DIR / "fixtures" / "usaspending_dod_fy2024_synthetic.json"
RAW_OUT_PATH = DEMO_DIR / "output" / "raw" / "usaspending_slice.json"

# One agency + one fiscal year, small page size — mirrors a single production search call.
AGENCY = "Department of Defense (toptier code 097)"
FISCAL_YEAR = 2024
PAGE_SIZE = 100
FIXTURE_ROWS = 300
# Fixed so the whole demo is deterministic (production uses date.today(); a demo that
# must be byte-reproducible in CI cannot). FY2024 close of business.
SNAPSHOT_DATE = date(2024, 10, 1)
_SEED = 20240701

SYNTHETIC_WARNING = (
    "SYNTHETIC DATA — deterministically generated by pipeline_demo/extract.py "
    "--generate-fixture. NOT real USAspending records. No value represents any real "
    "federal award, vendor, agency, or person. For pipeline-pattern demonstration only."
)

# ─── Deterministic synthetic pools (all fictional) ────────────────────────────
# NAICS split mirrors config/sources.yaml (always-relevant vs conditional vs out-of-scope).
_NAICS_ALWAYS = ["541511", "541512", "541513", "541519", "518210"]
_NAICS_CONDITIONAL = ["541330", "541611", "541690"]
_NAICS_OUT_OF_SCOPE = ["236220", "238210", "561210", "811310", "332312"]
_PSC_RELEVANT = ["D307", "D399", "DA01", "D302", "D310"]
_PSC_OUT_OF_SCOPE = ["R425", "S206", "Z2AA", "J099", "W070"]

_SUBAGENCIES = [
    "Department of the Army", "Department of the Navy", "Department of the Air Force",
    "Defense Health Agency", "Defense Logistics Agency", "Defense Information Systems Agency",
]
# Clearly fictional vendor names (no real business).
_VENDORS = [
    "Meridian Cyber Solutions (synthetic)", "Cascade Defense Systems (synthetic)",
    "Ironwood Federal LLC (synthetic)", "BlueHarbor Technologies (synthetic)",
    "Summit Signal Group (synthetic)", "Redstone Data Works (synthetic)",
    "Aegis Cyber Partners (synthetic)", "Northstar IT Services (synthetic)",
]
# Keyword-bearing descriptions (drive the cyber/IT classification signal).
_CYBER_IT_DESCRIPTIONS = [
    "Cybersecurity operations and RMF support services",
    "NIST 800-171 CMMC compliance advisory services",
    "Enterprise IT help desk and service desk support",
    "Network operations and SOC continuous monitoring",
    "Cloud migration and DevSecOps engineering support",
    "Zero trust architecture and identity and access management (IAM)",
    "Vulnerability management and penetration testing services",
    "Data analytics platform modernization and database administration",
    "Endpoint detection and response (EDR) managed services",
    "Information assurance and cyber defense operations support",
]
_OUT_OF_SCOPE_DESCRIPTIONS = [
    "Base facilities grounds maintenance services",
    "Medical supply logistics and warehousing",
    "Vehicle fleet maintenance and repair services",
    "Construction of a covered storage facility",
    "Food service operations at a dining facility",
]
_STATES_SERVED = ["VA", "MD", "DC", "TX", "CO", "AL", "GA"]
_STATES_OTHER = ["CA", "NY", "FL", "WA", "OH"]
_EXTENT_CODES = ["A", "D", "F", "C", "G"]          # A/D/F competitive; C/G not
_SET_ASIDE_CODES = ["NONE", "SBA", "SDVOSBC", "8AN", ""]
_AWARD_TYPES = ["DEFINITIVE CONTRACT", "DELIVERY ORDER", "BPA CALL"]
_PRICING_CODES = ["J", "U", "S"]                    # FFP / T&M / cost-plus proxies


def _iso(d: date) -> str:
    return d.isoformat()


def generate_fixture(rows: int = FIXTURE_ROWS) -> dict:
    """Build the deterministic synthetic raw-JSON slice. Same seed -> same bytes."""
    rng = random.Random(_SEED)
    results = []
    for i in range(rows):
        # Weighted NAICS/description so the slice yields a realistic cyber/IT vs
        # out-of-scope mix (mirrors production recall, then filters to candidates).
        bucket = rng.random()
        if bucket < 0.55:
            naics = rng.choice(_NAICS_ALWAYS)
            desc = rng.choice(_CYBER_IT_DESCRIPTIONS)
            psc = rng.choice(_PSC_RELEVANT)
        elif bucket < 0.75:
            naics = rng.choice(_NAICS_CONDITIONAL)
            desc = rng.choice(_CYBER_IT_DESCRIPTIONS)      # conditional NAICS needs a keyword
            psc = rng.choice(_PSC_RELEVANT + _PSC_OUT_OF_SCOPE)
        else:
            naics = rng.choice(_NAICS_OUT_OF_SCOPE)
            desc = rng.choice(_OUT_OF_SCOPE_DESCRIPTIONS)
            psc = rng.choice(_PSC_OUT_OF_SCOPE)

        # Award value: ~20%% below the $250k min (dropped as candidates), rest above.
        if rng.random() < 0.2:
            amount = round(rng.uniform(50_000, 249_000), 2)
        else:
            amount = round(rng.uniform(300_000, 80_000_000), 2)

        # Expiration mix relative to the fixed snapshot: active / grace / stale / missing.
        roll = rng.random()
        if roll < 0.62:                                    # active (future end)
            current_end = SNAPSHOT_DATE + timedelta(days=rng.randint(20, 900))
        elif roll < 0.74:                                  # grace (expired 1-90 days)
            current_end = SNAPSHOT_DATE - timedelta(days=rng.randint(1, 90))
        elif roll < 0.86:                                  # stale (expired > 90 days)
            current_end = SNAPSHOT_DATE - timedelta(days=rng.randint(120, 2000))
        else:                                              # missing end date -> Data Gap
            current_end = None

        if current_end is not None and rng.random() < 0.6:
            potential_end = current_end + timedelta(days=rng.randint(0, 365))
        else:
            potential_end = None

        start = (current_end - timedelta(days=rng.randint(365, 1460))) if current_end else None

        piid = f"SYN{FISCAL_YEAR}{i:04d}"
        parent = f"SYNIDV{FISCAL_YEAR}{rng.randint(1, 40):03d}" if rng.random() < 0.4 else None

        title = desc
        # Inject a few deterministic data-quality problems to exercise the flags /
        # quarantine path (garbled, code-prefix, short) — mirrors real raw dumps.
        if i % 47 == 0:
            title = f"{100000 + i}!RAW FPDS RECORD DUMP!! {desc}"      # garbled prefix + '!!'
        elif i % 53 == 0:
            title = f"IGF::OT::IGF {desc}"                             # code prefix
        elif i % 61 == 0:
            title = "Help desk"                                        # short (<10 chars)
        elif i % 97 == 0:
            title = desc + " " + ("X" * 420)                           # > 400 chars -> garbled

        results.append({
            "generated_internal_id": piid,
            "Award ID": piid,
            "award_type": rng.choice(_AWARD_TYPES),
            "Recipient Name": rng.choice(_VENDORS),
            "Recipient UEI": f"SYNUEI{i:06d}",
            "Awarding Agency": "Department of Defense",
            "Awarding Sub Agency": rng.choice(_SUBAGENCIES),
            "Award Amount": amount,
            "Start Date": _iso(start) if start else None,
            "End Date": _iso(current_end) if current_end else None,
            "potential_end_date": _iso(potential_end) if potential_end else None,
            "naics_code": naics,
            "psc_code": psc,
            "Description": title,
            "Place of Performance State Code": rng.choice(_STATES_SERVED + _STATES_OTHER),
            "extent_competed_code": rng.choice(_EXTENT_CODES),
            "type_of_set_aside_code": rng.choice(_SET_ASIDE_CODES),
            "type_of_contract_pricing_code": rng.choice(_PRICING_CODES),
            "number_of_offers_received": rng.choice([None, 1, 2, 3, 5, 8]),
            "referenced_idv_piid": parent,
        })

    return {
        "_synthetic": True,
        "_warning": SYNTHETIC_WARNING,
        "source_system": "USAspending (synthetic offline fixture)",
        "source_endpoint": "spending_by_award",
        "agency": AGENCY,
        "fiscal_year": FISCAL_YEAR,
        "page_size": PAGE_SIZE,
        "snapshot_date": _iso(SNAPSHOT_DATE),
        "seed": _SEED,
        "record_count": len(results),
        "results": results,
    }


def write_fixture(path: Path = FIXTURE_PATH) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = generate_fixture()
    path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    return path


def load_offline_fixture(path: Path = FIXTURE_PATH) -> list:
    """Read the committed synthetic fixture and return its raw result records."""
    if not path.exists():
        raise FileNotFoundError(
            f"Synthetic fixture not found at {path}. Generate it with "
            f"`python pipeline_demo/extract.py --generate-fixture`."
        )
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not payload.get("_synthetic"):
        raise ValueError(f"Fixture {path} is not flagged _synthetic — refusing to use it.")
    return payload["results"]


def fetch_online(agency_code: str = "097", fiscal_year: int = FISCAL_YEAR, page_size: int = PAGE_SIZE) -> list:
    """Best-effort LIVE pull from USAspending spending_by_award (opt-in; NOT used by CI).

    The live search API is known-unreliable (intermittent 503s), so this path is
    provided only to show the real request shape. `requests` is imported lazily so
    the offline demo has no network dependency at import time.
    """
    import requests  # noqa: PLC0415 — lazy so --offline never needs the network

    url = "https://api.usaspending.gov/api/v2/search/spending_by_award/"
    body = {
        "filters": {
            "award_type_codes": ["A", "B", "C", "D"],
            "agencies": [{"type": "awarding", "tier": "toptier", "name": "Department of Defense"}],
            "time_period": [{"start_date": f"{fiscal_year - 1}-10-01", "end_date": f"{fiscal_year}-09-30"}],
        },
        "fields": ["Award ID", "Recipient Name", "Awarding Agency", "Award Amount", "End Date"],
        "page": 1,
        "limit": page_size,
    }
    resp = requests.post(url, json=body, timeout=30)
    resp.raise_for_status()
    return resp.json().get("results", [])


def run_extract(offline: bool = True, persist: bool = True) -> list:
    """Return the raw award slice. offline (default) reads the committed fixture."""
    if offline:
        records = load_offline_fixture()
    else:
        records = fetch_online()

    if persist:
        RAW_OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        RAW_OUT_PATH.write_text(
            json.dumps({"_synthetic": offline, "record_count": len(records), "results": records},
                       indent=2) + "\n",
            encoding="utf-8",
        )
    return records


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="pipeline_demo extract stage (synthetic USAspending slice).")
    grp = ap.add_mutually_exclusive_group()
    grp.add_argument("--offline", action="store_true", help="read the committed synthetic fixture (default)")
    grp.add_argument("--online", action="store_true", help="best-effort live USAspending pull (not for CI)")
    ap.add_argument("--generate-fixture", action="store_true", help="(re)generate and overwrite the committed fixture")
    args = ap.parse_args(argv)

    if args.generate_fixture:
        path = write_fixture()
        payload = json.loads(path.read_text(encoding="utf-8"))
        print(f"Wrote {payload['record_count']} synthetic rows -> {path.relative_to(DEMO_DIR.parent)}")
        return 0

    offline = not args.online
    records = run_extract(offline=offline)
    src = "committed synthetic fixture" if offline else "live USAspending API"
    print(f"extract: pulled {len(records)} raw award records from the {src}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
