"""
load.py — pipeline_demo stage 3 of 4.

Persists a MINI star schema to parquet (+ CSV, so validate.py can assert CSV<->Parquet
parity, mirroring scripts/validate_data.py). Mirrors the production load/export step
(src/export/powerbi_export.py + scripts/rebake_data.py) at tiny scale:

  fact_recompete_candidates   grain: one recompete candidate (FK -> dim_agency, dim_naics)
  dim_agency                  grain: DoD component (agency + subagency) rollup
  dim_naics                   grain: NAICS code rollup
  dashboard_kpi_summary       one row of headline KPIs, all re-derivable from the fact

Every KPI is computed straight from the fact table (never hand-set) so the validator's
"KPI re-derivable from facts" invariant holds. Output lands under pipeline_demo/output/
(gitignored — regenerated by run_all.py; the repo follows a data-DIET, don't-commit-
generated-artifacts convention).

Run:  python pipeline_demo/load.py   # reads the interim parquet, writes output/star/
"""

import sys
from pathlib import Path

import pandas as pd

DEMO_DIR = Path(__file__).resolve().parent
if str(DEMO_DIR) not in sys.path:
    sys.path.insert(0, str(DEMO_DIR))

import transform  # noqa: E402  (sibling module)

INTERIM_PATH = transform.INTERIM_OUT_PATH
STAR_DIR = DEMO_DIR / "output" / "star"

_TIER_1 = "Tier 1: Pursue Now"

FACT_COLUMNS = [
    "candidate_id", "piid", "referenced_idv_piid", "contract_title", "title_display",
    "agency", "subagency", "agency_key", "incumbent_vendor", "naics", "naics_key", "psc",
    "award_type", "selected_expiration_date", "expiration_date_basis", "days_until_expiration",
    "candidate_status", "expiration_bucket", "expiration_bucket_sort", "total_obligated_amount",
    "place_of_performance_state", "extent_competed_code", "type_of_set_aside_code",
    "classification_confidence", "number_of_offers_received", "source_url",
    "flag_garbled_title", "flag_code_prefix", "flag_short_title", "flag_stale_expiration",
    "flag_missing_end_date", "pursuit_score", "priority_tier",
]


def _build_dim_agency(fact: pd.DataFrame) -> pd.DataFrame:
    keys = fact[["agency", "subagency"]].drop_duplicates().sort_values(["agency", "subagency"]).reset_index(drop=True)
    keys["agency_key"] = keys.index + 1
    active = fact[fact["candidate_status"] == "active"]
    cand_counts = fact.groupby(["agency", "subagency"]).size().rename("candidate_count")
    active_counts = active.groupby(["agency", "subagency"]).size().rename("active_candidate_count")
    active_value = active.groupby(["agency", "subagency"])["total_obligated_amount"].sum().rename("active_pipeline_value")
    dim = (keys.set_index(["agency", "subagency"])
           .join([cand_counts, active_counts, active_value])
           .reset_index())
    dim[["active_candidate_count"]] = dim[["active_candidate_count"]].fillna(0).astype(int)
    dim["candidate_count"] = dim["candidate_count"].fillna(0).astype(int)
    dim["active_pipeline_value"] = dim["active_pipeline_value"].fillna(0.0)
    return dim[["agency_key", "agency", "subagency", "candidate_count",
                "active_candidate_count", "active_pipeline_value"]]


def _build_dim_naics(fact: pd.DataFrame) -> pd.DataFrame:
    keys = fact[["naics"]].drop_duplicates().sort_values("naics").reset_index(drop=True)
    keys["naics_key"] = keys.index + 1
    counts = fact.groupby("naics").size().rename("candidate_count")
    dim = keys.set_index("naics").join(counts).reset_index()
    dim["candidate_count"] = dim["candidate_count"].fillna(0).astype(int)
    return dim[["naics_key", "naics", "candidate_count"]]


def _build_kpi(fact: pd.DataFrame) -> pd.DataFrame:
    active = fact[fact["candidate_status"] == "active"]
    row = {
        "total_estimated_pipeline_value": round(float(fact["total_obligated_amount"].sum()), 2),
        "recompete_candidate_count": int(len(fact)),
        "tier_1_count": int((fact["priority_tier"] == _TIER_1).sum()),
        "active_candidate_count": int(len(active)),
        "active_pipeline_value": round(float(active["total_obligated_amount"].sum()), 2),
        "active_tier_1_count": int((active["priority_tier"] == _TIER_1).sum()),
        "expired_grace_count": int((fact["candidate_status"] == "expired_grace").sum()),
        "expired_stale_count": int((fact["candidate_status"] == "expired_stale").sum()),
        "data_gap_count": int((fact["priority_tier"] == "Data Gap").sum()),
        "garbled_title_count": int(fact["flag_garbled_title"].sum()),
        "average_pursuit_score": round(float(fact["pursuit_score"].mean()), 1),
        "snapshot_date": transform.SNAPSHOT_DATE.isoformat(),
        "scorer_version": transform.SCORER_VERSION,
    }
    return pd.DataFrame([row])


def _write(df: pd.DataFrame, name: str) -> None:
    df.to_parquet(STAR_DIR / f"{name}.parquet", index=False)
    df.to_csv(STAR_DIR / f"{name}.csv", index=False, encoding="utf-8")


def run_load(fact: pd.DataFrame) -> dict:
    """Split the modeled fact into a mini star schema and write parquet + CSV."""
    STAR_DIR.mkdir(parents=True, exist_ok=True)
    dim_agency = _build_dim_agency(fact)
    dim_naics = _build_dim_naics(fact)
    fact = fact.merge(dim_agency[["agency", "subagency", "agency_key"]], on=["agency", "subagency"], how="left")
    fact = fact.merge(dim_naics[["naics", "naics_key"]], on="naics", how="left")
    fact = fact.reindex(columns=FACT_COLUMNS)
    kpi = _build_kpi(fact)

    _write(fact, "fact_recompete_candidates")
    _write(dim_agency, "dim_agency")
    _write(dim_naics, "dim_naics")
    _write(kpi, "dashboard_kpi_summary")

    return {
        "fact_recompete_candidates": len(fact),
        "dim_agency": len(dim_agency),
        "dim_naics": len(dim_naics),
        "dashboard_kpi_summary": len(kpi),
        "output_dir": STAR_DIR,
    }


def main(argv=None) -> int:
    if not INTERIM_PATH.exists():
        print(f"load: interim table not found at {INTERIM_PATH}. Run transform first.", file=sys.stderr)
        return 1
    fact = pd.read_parquet(INTERIM_PATH)
    result = run_load(fact)
    print(f"load: wrote mini star schema to {result['output_dir'].relative_to(DEMO_DIR.parent)}/ — "
          f"fact={result['fact_recompete_candidates']}, dim_agency={result['dim_agency']}, "
          f"dim_naics={result['dim_naics']}, kpi={result['dashboard_kpi_summary']} row.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
